export const START_COUNTER = 'START_COUNTER'
export const RESET_COUNTER = 'RESET_COUNTER'
export const PAUSE_COUNTER = 'PAUSE_COUNTER'

export const CONNECT_SERVER = 'CONNECT_SERVER'
export const CONNECT_SERVER_SUCCESS = 'CONNECT_SERVER_SUCCESS'
export const CONNECT_SERVER_FAILED = 'CONNECT_SERVER_FAILED'
export const UPDATE_NUMBER = 'UPDATE_NUMBER'
